# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go get -d
    # - go get github.com/inconshreveable/mousetrap
    # you may remove this if you don't use vgo
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
# snapshot:
#   name_template: "{{ .Env.SNAPSHOT_VERSION }}"
archive:
  name_template: "{{ .ProjectName }}-{{ .Os }}"
  replacements:
    darwin: osx
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
brew:
  github:
    owner: michakfromparis
    name: homebrew-tap
  folder: Formula
  homepage: https://github.com/michakfromparis/sparks
  description: "Design, Build & Play Sparks applications"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
