# constants
# docker image name
IMAGE_NAME=sparks-builder
# Makefile directory
MAKEFILE_DIRECTORY=$(dir $(realpath $(firstword $(MAKEFILE_LIST))))
# default build output directory
ROOT_DIRECTORY=$(MAKEFILE_DIRECTORY)..
# default build output directory
SPARKS_EXECUTABLE=$(ROOT_DIRECTORY)/build/sparks/linux/sparks
# sparks sdk root directory
SPARKS_SDK_ROOT?=$(HOME)/Sources/Sparks
# sparks build root directory
BUILD_ROOT?=$(ROOT_DIRECTORY)/build/player

PREBUILD=\
cp $(SPARKS_EXECUTABLE) .

POSTBUILD=\
rm -f $(MAKEFILE_DIRECTORY)/sparks

PRERUN=\
mkdir -p $(BUILD_ROOT)

POSTRUN=\
du -hs $(BUILD_ROOT)/* | sed 's|$(BUILD_ROOT)/||'

RUNARGS=bash -c "sparks build --v --webgl /sparks"

VOLUMES=\
-v "$(SPARKS_SDK_ROOT)":/sparks	\
-v "$(BUILD_ROOT)":/build
